baseURL = "http://www.bilomax.com/"
languageCode = "en-us"
title = "Alex's blog"
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentCodeFences = true
metaDataFormat = "yaml"
comments = true
  

[Params]
    logo="https://avatars2.githubusercontent.com/u/1896566?s=400&u=a237a69974cb51c9cc143a30f387e9a5a720cfb8&v=4"
    dateFormat = "January 2, 2006"
    commit = false
    rss = true
    github= true
    twitter= true
    comments = true
    useChroma = false
    #  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1


[Author]
  name = "Alex Salomon"
  github = "bizoton19"
  twitter = "lex_salomon"
  
